### ISSUE TITLE
报错信息不发我很难帮你看啊

### ISSUE THREAD

**Issue by jiuchu** [DanKE123abc/CG163CheckinHelper#2]
报错信息不发我很难帮你看啊

_Originally posted by @DanKE123abc in https://github.com/DanKE123abc/CG163CheckinHelper/issues/1#issuecomment-1425906724_
       {"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python37/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python37/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python37/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 696, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 677, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 728, in exec_module\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 219, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 4, in &lt;module;&gt;\n    import requests\nModuleNotFoundError: No module named 'requests'","requestId":"a91da017-bdf7-4d45-8fb1-238527db596a","statusCode":443}

**Comment by DanKE123abc** [comment]
你没有安装requests。

新版本CheckinHelper中已经全部移除了内置的requests了，需要你自己手动安装一下。

**Comment by DanKE123abc** [comment]
我最近比较忙，之后会转移到httpx，requests作为备选方案。

**Comment by jiuchu** [comment]
> 我最近比较忙，之后会转移到httpx，requests作为备选方案。
大佬成功了，之前安装了，但是没有安装到src目录下，签到成功了，但是没有推送，pushid是关注测试号右边的微信号吗？如果是的话都没有填错。

**Comment by DanKE123abc** [comment]
看看这个视频
【3分钟部署云原神自动签到，每天白嫖15分钟-哔哩哔哩】 https://b23.tv/QAFRlfK
虽然不是部署这个但推送部分是一样的

**Comment by DanKE123abc** [comment]
具体情况看errcode查文档

文档地址: wechatpush.dkdk.eu.org

**Comment by jiuchu** [comment]
> wechatpush.dkdk.eu.org

解决了感谢，原因是24小时没有和我的接口测试号发生交互发送条消息就可以了。没想到大佬才是中学生啊。厉害厉害！
