### ISSUE TITLE
大佬 网易云游戏推送能不能换一个推送

### ISSUE THREAD

**Issue by jiuchu** [DanKE123abc/CG163CheckinHelper#3]
那个微信的必须隔一段时间给它发送消息 不然报错不推送

**Comment by DanKE123abc** [comment]
之后推个大更新，支持多种推送方案

**Comment by jiuchu** [comment]
> 之后推个大更新，支持多种推送方案

好的辛苦了 问下cookie是多久到期呢？

**Comment by DanKE123abc** [comment]
没测过
&nbsp;


蛋壳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月18日(星期六) 晚上6:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DanKE123abc/CG163CheckinHelper] 大佬 网易云游戏推送能不能换一个推送 (Issue #3)





  
之后推个大更新，支持多种推送方案
  
好的辛苦了 问下cookie是多久到期呢？
